name: 🍪 Add New Flavor
description: Suggest a new Oreo flavor to add to the checklist
title: "[Flavor Suggestion] Add <Flavor Name> Oreo"
labels: ["enhancement", "flavor-suggestion"]
body:
  - type: input
    id: flavor_name
    attributes:
      label: What is the flavor name?
      description: Be specific, e.g., "Java Chip", "Pumpkin Spice", or "Wasabi"
      placeholder: e.g. "Brookie-O"
    validations:
      required: true

  - type: dropdown
    id: flavor_category
    attributes:
      label: What category does it belong to?
      options:
        - Classic
        - Limited Edition / Seasonal
        - International / Rare
        - Novelty / Collab
        - Not Sure
    validations:
      required: true
