name: General Question
description: Ask a general question about the Oreo Flavor Checklist
title: "[QUESTION] "
labels: ["question"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question! Please fill out the form below to help us understand your question better.

  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Please describe your question in detail.
      placeholder: Tell us what you'd like to know...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - General usage
        - Oreo flavors
        - Checklist format
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about your question here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false
